---
title: "Inferência_de_raiz"
output: html_document
Author: Dante von Zuben
---

Chamando os pacotes e lendo o arquivo .csv com os genes de interesse

```{r}

library(AnnotationHub)
library(RedeR)
library(igraph)
library(RColorBrewer)
library(geneplast)
library(dplyr)
library(readr)

set.seed(1)

Astrocyte_Markers <- read.csv(file = "Astrocyte_Markers - Página1.csv", header = T)
```


Carregando o dataset, criando uma conexão annotationHub e uma query para os recursos do geneplast
```{r}
ah <- AnnotationHub()

meta <- query(ah, "geneplast")


load(meta[["AH83116"]])

ogr <- groot.preprocess(cogdata=cogdata, phyloTree=phyloTree,cogids = Astrocyte_Markers$cog, spid="9606")

ogr <- groot(ogr, nPermutations=1000, verbose=FALSE)

res <- groot.get(ogr, what="results")
```

Plotando as árvores com os enraizamentos dos genes de interesse
```{r}
groot.plot(ogr, whichOG="COG0580", cex.lab = 0.1, cex.nodes = 0.3, fname="results/gproot")
groot.plot(ogr, whichOG="KOG0200", cex.lab = 0.1, cex.nodes = 0.3, fname="results/gproot")
groot.plot(ogr, whichOG="COG1012", cex.lab = 0.1, cex.nodes = 0.3, fname="results/gproot")
groot.plot(ogr, whichOG="NOG07029", cex.lab = 0.1, cex.nodes = 0.3, fname="results/gproot")
groot.plot(ogr, whichOG="NOG26751", cex.lab = 0.1, cex.nodes = 0.3, fname="results/gproot")
```

Nomeando os clados do enraizamento
```{r}
SOURCES <- list(
  STRING_SPECIES = "https://stringdb-static.org/download/species.v11.5.txt",
  EUKARYOTA_TREE = "https://raw.githubusercontent.com/dalmolingroup/neurotransmissionevolution/ctenophora_before_porifera/data/hybrid_tree_modified.nwk",
  CLADE_NAMES = "https://raw.githubusercontent.com/dalmolingroup/neurotransmissionevolution/ctenophora_before_porifera/analysis/geneplast_clade_names.tsv"
)

lca_names <- read_table(SOURCES$CLADE_NAMES)

groot_df <- res %>%  
  tibble::rownames_to_column("cog_id") %>%
  select(cog_id, root = Root) %>%
  left_join(lca_names) %>%
  left_join(Astrocyte_Markers, by = c("cog_id" = "cog"))

write.csv(groot_df, file = "results/enraizamento_genes_astrocitos.csv", row.names = F)

```